name: macOS Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Run unit tests
        run: xcodebuild -project DevTools.xcodeproj -scheme DevTools -destination 'platform=macOS' test | xcpretty
        env:
          NSUnbufferedIO: YES

