name: macOS Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Select Xcode 16
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.x"
      - name: Install xcpretty
        run: gem install xcpretty --no-document
      - name: Run unit tests
        run: |
          set -o pipefail
          xcodebuild \
            -project DevTools.xcodeproj \
            -scheme DevTools \
            -destination 'platform=macOS' \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            test | xcpretty
        env:
          NSUnbufferedIO: YES


